sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  # Use GCC 5 instead of the default
  - export CC=gcc-5 CXX=g++-5

  # cpp-coveralls
  - pip install --user cpp-coveralls

install:
  # Required libraries
  - sudo apt-get --assume-yes install libcairo2-dev libpango1.0-dev libglib2.0-dev libimlib2-dev libxinerama-dev libx11-dev libxdamage-dev libxcomposite-dev libxrender-dev libxrandr-dev librsvg2-dev libstartup-notification0-dev libcurl4-openssl-dev

  # For more detailed AddressSanitizer reports
  - sudo apt-get --assume-yes install binutils

  # For running some tests
  - sudo apt-get --assume-yes install xvfb xauth

  # For Coveralls integration
  - sudo apt-get --assume-yes install lcov curl

  # For documentation build
  - sudo apt-get --assume-yes install pandoc

before_script:
  - mkdir "${TRAVIS_BUILD_DIR}/build"
  - cd "${TRAVIS_BUILD_DIR}/build"
  - cmake "${TRAVIS_BUILD_DIR}" -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON

script:
  # Verify tint3 builds and passes tests
  - cd "${TRAVIS_BUILD_DIR}/build"
  - make all test

  # Verify the installation script works, then clean up
  - sudo make install DESTDIR=/opt/tint3 && sudo rm -rf /opt/tint3

after_success:
  # Upload coverage data to Coveralls
  - >-
    coveralls
    --root "${TRAVIS_BUILD_DIR}"
    --build-root "${TRAVIS_BUILD_DIR}/build"
    --exclude build
    --exclude abseil-cpp
    --exclude external_includes
    --exclude test
    --exclude-pattern '.*_test\.cc$'
    --exclude-lines-pattern '.*_test\.cc$'
    --gcov-options '\-lp'

notifications:
  irc:
    channels:
      - "chat.freenode.net#tint3"
    on_success: change
    on_failure: always
    use_notice: true
